### ISSUE TITLE
Create UI Design and document it

### ISSUE THREAD

**Issue by MadhavanKR** [airavata-courses/CloudElves#10]

**Comment by navkar14** [comment]
Updated the UI design draft.
[UI Diagram](https://github.com/airavata-courses/CloudElves/blob/project_1/feature_UI/navkar/forecast-ui/documents/UI_diagram.jpeg)
Commit link [here](https://github.com/airavata-courses/CloudElves/commit/af2ba5c34d252079a858c3d094f4ccb29630aca4)
