### ISSUE TITLE
Implement data ingestor microservice

### ISSUE THREAD

**Issue by MadhavanKR** [airavata-courses/CloudElves#11]

**Comment by ayushsanghavi** [comment]
https://github.com/airavata-courses/CloudElves/commit/9bd27586895932132bf86560e8c198a0a021a533#diff-3388fafeb871967edfa540c662db1baf75134cc5407b80734779bb69b179d8ab

Updated diagram for data ingestor microservice

**Comment by ayushsanghavi** [comment]
Enhanced code to avoid docker container crashes : 
https://github.com/airavata-courses/CloudElves/commit/6da31b031391cdaaf903cea655977d31e85a14aa
