### ISSUE TITLE
Feed back - Team Garuda

### ISSUE THREAD

**Issue by rishi1596** [airavata-courses/CloudElves#52]
Hi team,
The documentation part is extremely good. I appreciate your efforts in making the wiki page so informative.
Regarding the project, the project runs as expected kudos for that.
Suggestions - 1. UI could be approved 
2. Access token shouldn't be visible on the web application (This might cause security issues).

**Comment by ayushsanghavi** [comment]
Hi Team Garuda,
Thank you for your constructive feedback.
We will make sure, the access token is either masked as a serial number or something.

-Team CloudElves.
