### ISSUE TITLE
Implement Frontend - UI

### ISSUE THREAD

**Issue by MadhavanKR** [airavata-courses/CloudElves#6]

**Comment by navkar14** [comment]
Created basic UI structure which includes the following:
1. Creating required pages.
2. Implementing traversal between them.
3. Implemented Google OAuth sign-in feature.
Commit link [here](https://github.com/airavata-courses/CloudElves/commit/79cb0249ad69ceb2324e0108557f1aed489d34c9)

**Comment by navkar14** [comment]
1. Implemented user authentication and data retrieval management.
2. Implemented api calls executing user requests.
3. Bug fixes and code cleaning.
Commit link [here](https://github.com/airavata-courses/CloudElves/commit/9f2b78e30c8afc8225784c5620c37be3a42ece7b)
