### ISSUE TITLE
Evaluate Google sign in and implement 

### ISSUE THREAD

**Issue by MadhavanKR** [airavata-courses/CloudElves#7]

**Comment by navkar14** [comment]
1. Exploring Google Sign-in feature and deciding the optimal method to incorporate sign-in with Google.

**Comment by navkar14** [comment]
Implemented Google OAuth Sign-in feature with user session and data management features.
Commit link [here](https://github.com/airavata-courses/CloudElves/commit/79cb0249ad69ceb2324e0108557f1aed489d34c9)
