### ISSUE TITLE
Document installation for Frontend

### ISSUE THREAD

**Issue by MadhavanKR** [airavata-courses/CloudElves#8]

**Comment by navkar14** [comment]
Add steps to install and run react app to Readme.

**Comment by navkar14** [comment]
Updated the readme with installation steps.
[Readme](https://github.com/airavata-courses/CloudElves/blob/project_1/feature_UI/navkar/forecast-ui/README.md)
Commit link [here](https://github.com/airavata-courses/CloudElves/commit/137992fb8117f18ad85ef34233c42c1929883ef9)
